apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "vllm.fullname" . }}
  labels:
    {{- include "vllm.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: {{ include "vllm.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  policyTypes: [Ingress]
  ingress:
    - ports:
        - protocol: TCP
          port: 8000
